### ISSUE TITLE
微软接口和参数

### ISSUE THREAD

**Issue by Mu-Yue** [buming98/skype4java#1]
你好，问一下是怎样找的接口的参数？

**Comment by buming98** [comment]
web端用浏览器抓包

**Comment by Mu-Yue** [comment]
这个我知道，也用过一些抓包工具，但是请求太多了，不知道哪个是主要的，有什么办法知道哪些是流程必须的请求😂

**Comment by buming98** [comment]
> 这个我知道，也用过一些抓包工具，但是请求太多了，不知道哪个是主要的，有什么办法知道哪些是流程必须的请求😂

这个自行研究，本项目不提供教学服务
